### PR TITLE
Feature/members

### PR DESCRIPTION
**Pull request by jessicafarias**
This Project is a Members-Only Web App called **The Burn Book** built using Ruby on Rails, to implement the creation of a lightweight version web app where you can post "burns" (mean stuff about others), BUT you can only see them when you're signed up/in. We also got some experience using Devise in the process. This project showcases a User Role system giving the web application and native application feel all within the browser. We used Rails generators to help scaffold views. In this app the CRUD principles are used, where you can:

    Create
    Read
    Update
    Destroy
    Both "Burns" and Users.

### CODE REVIEW

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great start @team :clap: However some changes need to be implemented in order to get approval for this project. Check :arrow_down: 
#### Implementation (required) :warning: 
* [x] Only used routes should be defined
- use :only to define used routes for burns
#### views (required)
* [x] View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)
* [x] There shoud be absolutely NO logic in views(ifs, loops...).

  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
### That's it :relieved: When finished, kindly submit a code re-review request :pray: 
Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by aracelicaes** [comment]
Ahmed, we thank you for your timely feedback. We have reviewed the following requests:

_**views (required)
  
   View-related logic can be encapsulated in View helpers (app/helpers/*_helper.rb)
   There should be absolutely NO logic in views(ifs, loops...).**_

However, we tried looking for documentation about this and were not able to find something that fully justifies this change. We believe that it doesn't represent proper optimization and it will make the loading time heavier, increasing the traffic of the page because of the additional files. We also looked at the blog link you shared and it doesn't fully explain the reasons behind this logic. Could you please help us by issuing official documentation about rails that can explain this requirement in detail?

**Comment by aracelicaes** [comment]
> ### Great start @team clap However some changes need to be implemented in order to get approval for this project. Check arrow_down
> #### Implementation (required) warning
> 
>     * [ ]  Only used routes should be defined
> 
> 
>     * use :only to define used routes for burns
> 
> 
> #### views (required)
> 
>     * [ ]  View-related logic can be encapsulated in View helpers (app/helpers/*_helper.rb)
> 
>     * [ ]  There shoud be absolutely NO logic in views(ifs, loops...).
>       > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
> 
>     * [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
> 
> 
> ### That's it relieved When finished, kindly submit a code re-review request pray
> 
> Happy coding v
> **_Ahmed Mahfoudh_**

Ahmed,
We thank you for your timely feedback. We have reviewed the following requests:

```
views (required)
  
   View-related logic can be encapsulated in View helpers (app/helpers/*_helper.rb)
   There should be absolutely NO logic in views(ifs, loops...).
```

However, we tried looking for documentation about this and were not able to find something that fully justifies this change. We believe that it doesn't represent proper optimization and it will make the loading time heavier, increasing the traffic of the page because of the additional file. We also looked at the blog and it doesn't fully explain the logic behind making this change. Could you please help by us issuing official documentation about rails that can explain this requirement in detail?

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, everything works fine, but there are a few more things required. 
### General
- Hello Team in order to move forward you need to work on all requirement requested by previous TSE.
### [ OPTIONAL ]
You can use this article as a guide 
https://shehantips.com/10-01-2019/
https://rails.devcamp.com/trails/dissecting-rails-5/campsites/working-views-rails/guides/guide-view-helpers-rails-5

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by mosesogwo — APPROVED** [review]
**Hello :wave: Well done :+1: Your project is approved!**

You can now merge this PR.

_**Cheers :stars:**_

### Status: Approved :heavy_check_mark:

**Pull request merged**
